name: editor
description: Flutter code editor and preview built with dart_eval
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_eval: ^0.4.7
  code_editor: ^1.3.2
  scoped_model: ^2.0.0
  event_bus: ^2.0.0
  file_selector: ^0.9.2
  file: ^6.1.4
  built_value: ^8.0.0
  equatable: ^2.0.5
  dart_style: ^2.0.0
  platformx: ^1.1.0
  _fe_analyzer_shared: 46.0.0
  fs_shim: ^2.0.3
  yaml: ^3.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^8.4.1
  build_runner: ^2.2.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/syntax/Dart.syntax
    - assets/syntax/JSON.syntax
    - assets/syntax/Protobuf.syntax
    - assets/syntax/SQL.syntax
    - assets/syntax/YAML.syntax
  fonts:
    - family: Hack
      fonts:
        - asset: fonts/Hack/Hack-Regular.ttf
          weight: 400
        - asset: fonts/Hack/Hack-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Hack/Hack-Bold.ttf
          weight: 700
        - asset: fonts/Hack/Hack-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900